name: Build Image and Test
on:
  push:
env:
  IMAGE_TAG: issue-docker-gha-load-very-slow:${{github.sha}}
jobs:
  ActionWithoutCache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          context: .
          file: ./Dockerfile
          tags: ${{env.IMAGE_TAG}}
      - name: Run Docker image
        id: docker-run
        shell: bash
        run: |
          docker image ls
          echo "Running Docker image ${IMAGE_TAG}"
          docker run --init --rm "${IMAGE_TAG}"
