name: Build Image and Test
on:
  push:
jobs:
  UseGhcrAndCache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
      - name: Run Docker image
        id: docker-run
        shell: bash
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          echo "Running Docker image ${IMAGE_TAG}"
          docker run --init --rm "${IMAGE_TAG}"
          docker buildx rm container
# dummy1
