name: Build Image and Test
on:
  push:
jobs:
  UseGhcrAndCache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{github.sha}}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
      - name: Run Docker image
        id: docker-run
        shell: bash
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
        run: |
          echo "Running Docker image ${IMAGE_TAG}"
          docker run --init --rm "${IMAGE_TAG}"
          docker buildx rm container
# dummy1
